package me.blvckbytes.blvcksys.persistence;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/*
  Author: BlvckBytes <blvckbytes@gmail.com>
  Created On: 05/04/2022

  Marks a field of a model as it's identifier. These fields will always be
  auto-generated by the persistence. Supported types include UUIDs and Integers.
*/
@Target({ ElementType.FIELD })
@Retention(RetentionPolicy.RUNTIME)
public @interface ModelIdentifier {}
