name: '&5Brauen'
representitive:
  name: '&5Brauer'
  amount: 1
  type: DIAMOND_PICKAXE
  lore:
    - '&cLine 1'
    - '&bLine 2'
    - '&dLine 3'
  flags:
    - HIDE_ATTRIBUTES
  enchantments:
    - DAMAGE_ALL:5
stages:
  -
    name: '&5Brauer I'
    representitive:
      name: '&5Brauer I'
      amount: 1
      type: POTION
      lore:
        - '&7Braue 3 Regenerations- oder Heilungstränke'
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          anyOf: true
          effects:
            -
              effectType: REGENERATION
              amplifier: 1
              duration: 450
            -
              effectType: HEAL
              amplifier: 1
  -
    name: '&5Brauer II'
    representitive:
      name: '&5Brauer II'
      amount: 1
      type: POTION
      lore:
        - '&7Braue 5 Schadentränke'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          effects:
            -
              effectType: HARM
  -
    name: '&5Brauer III'
    representitive:
      name: '&5Brauer III'
      amount: 1
      type: POTION
      lore:
        - '&7Braue eine Awkward Potion'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 1
        parameters:
          effects:
            -
              potionType: AWKWARD
