name: '&5Brauen'
representitive:
  name: '&7» &5Brauer'
  type: BREWING_STAND
  lore:
    - ' '
    - '&7Braue verschiedene Tränke mit'
    - '&7Hilfe eines &dBraustandes&7.'
    - ' '
    - '&7Verfügbare Stufen: &d{{num_stages}}'
    - '&7Aktuelle Stufe: &d{{curr_stage}}'
    - '&7Fortschritt: &d{{progress}}'
stages:
  -
    name: '&5Brauer I'
    representitive:
      name: '&7» &5Brauer I'
      type: POTION
      color: 255 0 0
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7Regeneration II oder Heilung II'
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          anyOf: true
          effects:
            -
              effectType: REGENERATION
              amplifier: 1
              duration: 450
            -
              effectType: HEAL
              amplifier: 1
  -
    name: '&5Brauer II'
    representitive:
      name: '&7» &5Brauer II'
      amount: 1
      type: POTION
      color: 255 0 128
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7Schadentränke'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          effects:
            -
              effectType: HARM
  -
    name: '&5Brauer III'
    representitive:
      name: '&7» &5Brauer III'
      amount: 1
      type: POTION
      color: 0 255 0
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7komische Tränke'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 1
        parameters:
          effects:
            -
              potionType: AWKWARD
