name: '&5Brauen'
representitive:
  name: '&7» &5Brauer'
  type: BREWING_STAND
  lore:
    - ' '
    - '&7Braue verschiedene Tränke mit'
    - '&7Hilfe eines &dBraustandes&7.'
    - ' '
    - '&7Verfügbare Stufen: &d{{num_stages}}'
    - '&7Aktuelle Stufe: &d{{curr_stage}}'
    - '&7Fortschritt: {{progress_bar}} &7(&a{{progress}}&7)'
stages:
  -
    name: '&5Brauer I'
    representitive:
      name: '&7» &5Brauer I'
      type: POTION
      baseEffect:
        type: REGEN
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7Regeneration II'
        - '&7oder Heilung II und trinke diese &d{{task_1_completed}}&7/&d{{task_1_total}}&7.'
        - '&7Fortschritt: {{progress_bar}} &7(&a{{progress}}&7)'
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          anyOf: true
          effects:
            -
              effectType: REGENERATION
              amplifier: 1
              duration: 450
            -
              effectType: HEAL
              amplifier: 1
      -
        action: CONSUME
        count: 5
        parameters:
          # TODO: Add potion effects to itemstack parsing
          items:
            -
              type: POTION
  -
    name: '&5Brauer II'
    representitive:
      name: '&7» &5Brauer II'
      amount: 1
      type: SPLASH_POTION
      baseEffect:
        type: INSTANT_DAMAGE
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7Schadentränke'
        - '&7Fortschritt: {{progress_bar}} &7(&a{{progress}}&7)'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 5
        parameters:
          splash: true
          effects:
            -
              effectType: HARM
  -
    name: '&5Brauer III'
    representitive:
      name: '&7» &5Brauer III'
      amount: 1
      type: POTION
      baseEffect:
        type: AWKWARD
      flags:
        - HIDE_POTION_EFFECTS
      lore:
        - ' '
        - '&7Braue &d{{task_0_completed}}&7/&d{{task_0_total}} &7komische Tränke'
        - '&7Fortschritt: {{progress_bar}} &7(&a{{progress}}&7)'
    tasksInOrder: true
    tasks:
      -
        action: BREWING
        count: 1
        parameters:
          effects:
            -
              potionType: AWKWARD
